//
//  MessagesViewController.m
//  MessagesExtension
//
//  Created by HYZ on 16/11/10.
//  Copyright © 2016年 HYZ. All rights reserved.
//

#import "MessagesViewController.h"
#import<Messages/Messages.h>

@interface MessagesViewController ()<MSStickerBrowserViewDataSource>

@property(nonatomic)NSMutableArray * asrray;
@property(nonatomic,strong)MSStickerBrowserViewController  * MSVC;
@end

@implementation MessagesViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    _asrray = [[NSMutableArray alloc]initWithCapacity:5];
    for (int i = 1; i<=2; i++) {
        NSURL * url  = [[NSBundle mainBundle] URLForResource:[NSString stringWithFormat:@"Sticker %d",i] withExtension: @"png"];
        if (url) {
            MSSticker* sticker = [[MSSticker alloc]initWithContentsOfFileURL:url localizedDescription:@"" error:nil];
            [_asrray addObject:sticker];
        }
        
    }
    
    
    
    self.view.backgroundColor = [UIColor whiteColor];
    _MSVC = [[MSStickerBrowserViewController alloc]initWithStickerSize:MSStickerSizeLarge];
    [self addChildViewController:_MSVC];
    [self.view addSubview:_MSVC.view];
    _MSVC.stickerBrowserView.backgroundColor = [UIColor orangeColor];
    _MSVC.stickerBrowserView.dataSource =self;
     [self.view.topAnchor constraintEqualToAnchor:_MSVC.view.topAnchor].active = YES;
    [self.view.bottomAnchor constraintEqualToAnchor:_MSVC.view.bottomAnchor].active =YES;
     [self.view.rightAnchor constraintEqualToAnchor:_MSVC.view.rightAnchor].active =YES;
     [self.view.leftAnchor constraintEqualToAnchor:_MSVC.view.leftAnchor].active =YES;
    
    
    // Do any additional setup after loading the view.
}


-(NSInteger)numberOfStickersInStickerBrowserView:(MSStickerBrowserView *)stickerBrowserView
{
    return  _asrray.count;
}

-(MSSticker *)stickerBrowserView:(MSStickerBrowserView *)stickerBrowserView stickerAtIndex:(NSInteger)index
{
    return _asrray[index];
}


- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

#pragma mark - Conversation Handling

-(void)didBecomeActiveWithConversation:(MSConversation *)conversation {
    // Called when the extension is about to move from the inactive to active state.
    // This will happen when the extension is about to present UI.
    
    // Use this method to configure the extension and restore previously stored state.
}

-(void)willResignActiveWithConversation:(MSConversation *)conversation {
    // Called when the extension is about to move from the active to inactive state.
    // This will happen when the user dissmises the extension, changes to a different
    // conversation or quits Messages.
    
    // Use this method to release shared resources, save user data, invalidate timers,
    // and store enough state information to restore your extension to its current state
    // in case it is terminated later.
}

-(void)didReceiveMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when a message arrives that was generated by another instance of this
    // extension on a remote device.
    
    // Use this method to trigger UI updates in response to the message.
}

-(void)didStartSendingMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when the user taps the send button.
}

-(void)didCancelSendingMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when the user deletes the message without sending it.
    
    // Use this to clean up state related to the deleted message.
}

-(void)willTransitionToPresentationStyle:(MSMessagesAppPresentationStyle)presentationStyle {
    // Called before the extension transitions to a new presentation style.
    
    // Use this method to prepare for the change in presentation style.
}

-(void)didTransitionToPresentationStyle:(MSMessagesAppPresentationStyle)presentationStyle {
    // Called after the extension transitions to a new presentation style.
    
    // Use this method to finalize any behaviors associated with the change in presentation style.
}

@end
